CREATE TABLE IF NOT EXISTS Accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_num VARCHAR(12) UNIQUE DEFAULT NULL,
    user_id INT,
    account_type VARCHAR(15),
    balance DECIMAL(20, 2) DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES Users(id)
)